### PR TITLE
1 is truthy

### PR DESCRIPTION
**Pull request by bermarte**

### CODE REVIEW

**Comment by colevandersWands** [comment]
@bermarte , now I look closer at this file (thanks to your PR) I see it's more confusing than it needs to be.  a lot of double-negative going on.  Rather than fix this one line I'd rather rewrite the whole file to be more straight-forward.  Do you mind to do this?  If not I can take care of it

**Comment by bermarte** [comment]
@colevandersWands I am not sure how you want to rewrite it.

**Comment by colevandersWands** [comment]
@bermarte , not a problem.  I'll put my idea here in a review and we can look it over when you have time

**Comment by bermarte** [comment]
I found this other small issue. Please check this one out, it's a stripped example [arr.some(isNotANumber)].(http://localhost:4005?study=%7B%22permalink%22%3A%7B%22content%22%3A%22const%20sumEvenNumbers%20%3D%20(arr)%20%3D%3E%20%7B%5Cn%20%20const%20isNotANumber%20%3D%20(entry)%20%3D%3E%20%7B%5Cn%20%20%20%20const%20res%20%3D%20typeof%20entry%20!%3D%3D%20'number'%3B%5Cn%20%20%20%20console.log(entry%2C%20res)%3B%5Cn%20%20%20%20return%20res%3B%5Cn%20%20%7D%3B%5Cn%20%20%5Cn%20%20if%20(arr.some(isNotANumber))%20%7B%5Cn%20%20%20%20throw%20new%20TypeError('arr%20is%20not%20all%20numbers')%3B%5Cn%20%20%7D%5Cn%5Cn%20%20const%20sumOfEvens%20%3D%20arr%5Cn%20%20%20%20.filter(entry%20%3D%3E%20%7B%5Cn%20%20%20%20%20%20return%20entry%20%25%202%20%3D%3D%3D%200%3B%5Cn%20%20%20%20%7D)%5Cn%20%20%20%20.reduce((sum%2C%20next)%20%3D%3E%20%7B%5Cn%20%20%20%20%20%20return%20sum%20%2B%20next%3B%5Cn%20%20%20%20%7D)%3B%5Cn%20%20console.log(sumOfEvens)%3B%5Cn%20%20return%20sumOfEvens%3B%5Cn%7D%3B%5Cn%5Cnconst%20_1_arg%20%3D%20%5B1%2C%202%2C%203%5D%3B%5Cnconst%20_1_actual%20%3D%20sumEvenNumbers(_1_arg)%3B%5Cn%5Cnconst%20_2_arg%20%3D%20%5B4%2C%20'5'%2C%206%5D%3B%5Cnconst%20_2_actual%20%3D%20sumEvenNumbers(_2_arg)%3B%22%2C%22ext%22%3A%22.js%22%2C%22locals%22%3A%7B%22eval%22%3Atrue%2C%22flowchart%22%3Atrue%2C%22loopGuard%22%3A%7B%22active%22%3Afalse%2C%22max%22%3A100%7D%2C%22save%22%3Atrue%2C%22openIn%22%3A%22jsTutorLive%22%7D%2C%22queryValue%22%3A%22%22%2C%22base%22%3A%224-all-together-inline.js%22%7D%7D)

**Comment by bermarte** [comment]
@colevandersWands Can I close this PR without merging it?

**Comment by colevandersWands** [comment]
@bermarte , if the changes I pushed fix the issue then I you can use the "Close with comment" button.  Otherwise we can keep discussing and changing till it's good.  (pushing to master wasn't a good way for me to propose these changes)

**Comment by bermarte** [comment]
@colevandersWands sounds good to me. I'll save what I had edited into a Gist to see how it works. Now, the file `4-all-together-inline.js` is more like the others.

**Pull request closed without merging**
